# Header
navbar_brand: /images/logo.png
rss: /atom.xml
mastodon: https://masto.ai/@shaneschurch

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
- about
- archive
- tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: 'UA-74778051-1'
favicon: /favicon.ico
twitter_id: 'shaneschurch'
google_plus:
fb_admins:
fb_app_id:
